### ISSUE TITLE
Redis server cannot be connected

### ISSUE THREAD

**Issue by luchris** [RobiNN1/phpCacheAdmin#19] opened 2023-02-27 15:10 UTC
**phpCacheAdmin Version**: 
v1.5.1
**Cache**:

**PHP Version**: 
php 8.0.28
**Operating System**: 
Rocky Linux release 8.7 (Green Obsidian)
**Describe the issue**

Redis 5.0.3-5

Blank page after i clicked on Redis. Memcached and OPCache are ok

My config file

    'redis'         => [
        [
            'name' => 'localhost', // The server name (optional).
            'host' => '127.0.0.1', // Optional when a path is specified.
            'port' => 6379, // Optional when the default port is used.
            //'database'  => 0, // Default database (optional).
            //'username'  => '', // ACL - requires Redis >= 6.0 (optional).
            //'password'  => '', // Optional.
            //'authfile'  => '/run/secrets/file_name', // File with a password, e.g. Docker secrets (optional).
            //'path'      => '/var/run/redis/redis-server.sock', // Unix domain socket (optional).
            //'databases' => 16, // Number of databases, use this if the CONFIG command is disabled (optional).
            //'scansize'  => 1000, // Number of keys, the server will use the SCAN command instead of KEYS (optional).
        ],
    ],

I only changed Localhost to localhost

**Comment by luchris** [comment] 2023-02-27 15:58
Hi the error is :-

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///var/www/html/phpCacheAdmin/predis.phar/src/Client.php on line 0

I keep added memorylimit from 128M to -1 and finally the error became

PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/phpCacheAdmin/src/Dashboards/Redis/TypesTrait.php on line 257

**Comment by RobiNN1** [comment] 2023-02-27 16:48
I was not able to reproduce this and tests with only Predis are ok too https://github.com/RobiNN1/phpCacheAdmin/actions/runs/4284625400/jobs/7461843175

redis 5 - https://github.com/RobiNN1/phpCacheAdmin/actions/runs/4284694581/jobs/7462010360

Double check the `host` & `port` and server status. Maybe just redis server is too slow. Try it with increased `max_execution_time` in PHP.

---

Closing this because there are no problems with the code.

**Closed by RobiNN1** 2023-02-27 16:48 UTC

**Comment by luchris** [comment] 2023-02-27 17:09
I slowing increase memorylimit and max_exceution_time and ended up with
memorylimit = -1
max_execution_time = 600

host and port are correct

[root@fantastic rspamd]# netstat -tunlp | grep redis
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      624/redis-server 12

httpd does not have anymore error. Instead the webpage reads

Gateway Timeout

The gateway did not receive a timely response from the upstream server or application.
